[package]
name = "soco"
version = "0.1.0"
authors = ["Unreal Hoang <unrealhoang@gmail.com>"]

[dependencies]
github-rs = "0.6"
serde_json = "1.0"
regex = "1.0.0"
structopt = "0.2"
chrono = "0.4"
base64 = "0.9.2"